name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: |
          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json; skipping install."
          fi
      - name: Lint & Test (placeholder)
        run: |
          echo "No tests yet; placeholder CI passing."
